services:
  voice-agent:
    build:
      context: .
      dockerfile: Dockerfile.jetson
    working_dir: /app
    volumes:
      - ./:/app
    command: node voice-agent/dist/index.js
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - LLM_PROVIDER=openai
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - STT_PREFER_LOCAL=true
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=all
      - MCP_CONFIG_PATH=/app/mcp-config.json
    # Expose port 3000 for ESP32-S3 development (non-SSL WebSocket)
    ports:
      - "3000:3000"
    # GPU access for Jetson
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility]
    runtime: nvidia
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # HTTPS proxy for mobile access
  nginx-ssl:
    image: nginx:latest
    ports:
      - "80:80" # HTTP (redirects to HTTPS)
      - "443:443" # HTTPS
    volumes:
      - ./ssl:/etc/nginx/ssl
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./generate-ssl.sh:/generate-ssl.sh:ro
    depends_on:
      - voice-agent
    restart: unless-stopped
    command: ["sh", "/generate-ssl.sh"]

volumes:
  logs:
  uploads:
