services:
  voice-agent:
    image: dustynv/l4t-pytorch:r36.4.0
    working_dir: /app
    volumes:
      - ./:/app
    command: node voice-agent/dist/index.js
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - LLM_PROVIDER=openai
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - STT_PREFER_LOCAL=true
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=all
    ports:
      - "3000:3000"
    # GPU access for Jetson
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility]
    runtime: nvidia
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

 