# Development Docker Compose for macOS compatibility
# Usage: docker compose -f docker-compose.dev.yml up

services:
  mcp-voice-agent:
    build: .
    ports:
      - "3000:3000"  # Standard port mapping for macOS compatibility
    environment:
      - NODE_ENV=development
      - LLM_PROVIDER=openai
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - STT_PREFER_LOCAL=false  # Use cloud STT for development
      - DEBUG=*
    volumes:
      - ./data:/data
      - ./logs:/app/logs
      - ./uploads:/app/voice-agent/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  dev-tools-api:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    command: ["node", "mcp-servers/dev-tools-mcp/dist/http-server.js"]
    restart: unless-stopped
    depends_on:
      - mcp-voice-agent

  finance-api:
    build: .
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    command: ["node", "mcp-servers/finance-mcp/dist/http-server.js"]
    restart: unless-stopped
    depends_on:
      - mcp-voice-agent

volumes:
  logs:
  uploads: 