services:
  voice-agent:
    build:
      context: .
      dockerfile: Dockerfile.jetson
    working_dir: /app
    volumes:
      - ./:/app
    command: node voice-agent/dist/index.js
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - LLM_PROVIDER=openai
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - STT_PREFER_LOCAL=true
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=all
      - MCP_CONFIG_PATH=/app/mcp-config.json
    # Temporarily expose port for testing
    ports:
      - "3000:3000"
    # GPU access for Jetson
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility]
    runtime: nvidia
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # HTTPS proxy for mobile access
  nginx-ssl:
    image: nginx:latest
    ports:
      - "80:80"    # HTTP (redirects to HTTPS)
      - "443:443"  # HTTPS
    volumes:
      - ./ssl:/etc/nginx/ssl
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - voice-agent
    restart: unless-stopped
    command: |
      sh -c '
        mkdir -p /etc/nginx/ssl
        if [ ! -f /etc/nginx/ssl/cert.pem ]; then
          echo "Generating SSL certificate..."
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/key.pem -out /etc/nginx/ssl/cert.pem -subj "/C=US/ST=Production/L=Jetson/O=VoiceAgent/CN=192.168.1.108"
          echo "SSL certificate generated"
        fi
        nginx -g "daemon off;"
      '

volumes:
  logs:
  uploads: